//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCFSMSystem_ServerClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UFSM_AreaInfo
    {
        public int ID { get; set; }
        public int AreaNum { get; set; }
        public Nullable<byte> Attribute { get; set; }
        public Nullable<byte> PopQuality { get; set; }
        public Nullable<byte> BuildingFireResistanceRating { get; set; }
        public Nullable<byte> PopDensity { get; set; }
        public Nullable<byte> BuildingYears { get; set; }
        public Nullable<byte> FireSafetyPropaganda { get; set; }
        public Nullable<byte> PowerLineLoad { get; set; }
        public Nullable<byte> FireSafetyManagement { get; set; }
        public Nullable<byte> AgingOfPowerLines { get; set; }
        public Nullable<byte> FireInspectionOfKeyBuildings { get; set; }
        public Nullable<byte> TimeFactor { get; set; }
        public Nullable<byte> EconomicDensity { get; set; }
        public Nullable<byte> HighBuildingsNum { get; set; }
        public Nullable<byte> UndergroundCrowdedSpace { get; set; }
        public Nullable<byte> DensityOfKeyBuildings { get; set; }
        public Nullable<byte> RoadCongestion { get; set; }
        public Nullable<byte> BuildingDensity { get; set; }
        public Nullable<byte> DistributionOfInflammableStorage { get; set; }
        public Nullable<byte> FireStationCapacityCoverage { get; set; }
        public Nullable<byte> FireStationEquipment { get; set; }
        public Nullable<byte> PublicFireFacilities { get; set; }
        public Nullable<byte> DepartmentalEmergencyResponse { get; set; }
        public Nullable<byte> FireAndRescuePlan { get; set; }
        public Nullable<byte> KeyBuildingsFirePreventBuilt { get; set; }
        public Nullable<System.DateTime> AreaUploadTime { get; set; }
        public Nullable<short> AreaAssessmentYear { get; set; }
        public Nullable<byte> AreaRiskGrade { get; set; }
        public Nullable<int> AreaSize { get; set; }
        public Nullable<int> AreaPop { get; set; }
    }
}
